cpu-bind=MASK - gn56, task  2  0 [1922730]: mask 0xffff0000ffff0000ffffffffffffffffffff0000ffff0000ffffffffffffffff set
*******STARTING********
--- Running on Node Rank: 2 ---
Total Nodes: 4
--- CUDA_VISIBLE_DEVICES for this srun task: 0,1,2,3 ---
GPUs per Node: 4
Master Address: gn52
Master Port: 29500
-------------------------------------------
accelerate launch     --config_file /ceph/hpc/data/s24o01-42-users/translation_optimization/trl/accelerate_config.yaml     --num_machines 4     --machine_rank 2     --main_process_ip gn52     --main_process_port 29500     --num_processes 16     --deepspeed_hostfile /ceph/hpc/data/s24o01-42-users/translation_optimization/trl/result_dir/hostfile_62777308     --deepspeed_multinode_launcher standard     --rdzv_backend static     --same_network     --mixed_precision bf16     "train_curriculum.py"     --rank=64 --learning_rate=4e-7 --total_epochs=3 --beta=0.2 --curriculum_stage=0
-------------------------------------------
[2025-06-08 19:24:40,050] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
W0608 19:24:41.674000 1922780 torch/distributed/run.py:792] 
W0608 19:24:41.674000 1922780 torch/distributed/run.py:792] *****************************************
W0608 19:24:41.674000 1922780 torch/distributed/run.py:792] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0608 19:24:41.674000 1922780 torch/distributed/run.py:792] *****************************************
[2025-06-08 19:24:46,684] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-06-08 19:24:46,726] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-06-08 19:24:46,741] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-06-08 19:24:46,749] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Training data of type 'bad_lang_examples':    3489
Training data of type 'short_examples':       699
Training data of type 'choose_examples':      13379
Training data of type 'bad_format_examples':  3148
**************************************************
Training data of type 'bad_lang_examples':    3489Training data of type 'bad_lang_examples':   
 Training data of type 'short_examples':      3489 
699Training data of type 'short_examples':      
 Training data of type 'choose_examples':     699 
13379Training data of type 'choose_examples':     
 Training data of type 'bad_format_examples': 13379 
3148Training data of type 'bad_format_examples': 
 **************************************************3148

**************************************************
Training data of type 'bad_lang_examples':    3489
Training data of type 'short_examples':       699
Training data of type 'choose_examples':      13379
Training data of type 'bad_format_examples':  3148
**************************************************
Evaluation data size: 953
Evaluation data size: 953
Evaluation data size: 953
Evaluation data size: 953
Curriculum stage 0 training data size: 7336
Curriculum stage 0 training data size: 7336
Curriculum stage 0 training data size: 7336
Curriculum stage 0 training data size: 7336
Curriculum stage 1 training data size: 6689
Curriculum stage 1 training data size: 6689
Curriculum stage 1 training data size: 6689
Curriculum stage 1 training data size: 6689
Curriculum stage 2 training data size: 6690
Namespace(rank=64, learning_rate=4e-07, total_epochs=3, beta=0.2, curriculum_stage=0)
4e-07
Curriculum stage 2 training data size: 6690
Curriculum stage 2 training data size: 6690
Curriculum stage 2 training data size: 6690
Namespace(rank=64, learning_rate=4e-07, total_epochs=3, beta=0.2, curriculum_stage=0)
4e-07
Namespace(rank=64, learning_rate=4e-07, total_epochs=3, beta=0.2, curriculum_stage=0)
4e-07
World size: 16
Setting gradient accumulation steps to: 1
Namespace(rank=64, learning_rate=4e-07, total_epochs=3, beta=0.2, curriculum_stage=0)
4e-07
[2025-06-08 19:24:50,577] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-06-08 19:24:50,579] [INFO] [comm.py:658:init_distributed] cdb=None
Created datasets
Train dataset size: 7336
Validation dataset size: 953
Steps per epoch: 458
Evaluate each 229 steps
[2025-06-08 19:24:50,585] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-06-08 19:24:50,586] [INFO] [comm.py:658:init_distributed] cdb=None
Set up DPO configuration
Loading model from: cjvt/GaMS-9B-Instruct
[rank9]: Traceback (most recent call last):
[rank9]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train_curriculum.py", line 235, in <module>
[rank9]:     main(get_train_data(CURRICULUM_STAGE), val_data, args.rank, args.learning_rate, args.total_epochs, args.beta, CURRICULUM_STAGE)
[rank9]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train_curriculum.py", line 149, in main
[rank9]:     model = AutoModelForCausalLM.from_pretrained(
[rank9]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
[rank9]:     return model_class.from_pretrained(
[rank9]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
[rank9]:     return func(*args, **kwargs)
[rank9]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4336, in from_pretrained
[rank9]:     config = cls._autoset_attn_implementation(
[rank9]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2109, in _autoset_attn_implementation
[rank9]:     cls._check_and_enable_flash_attn_2(
[rank9]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2252, in _check_and_enable_flash_attn_2
[rank9]:     raise ImportError(f"{preface} the package flash_attn seems to be not installed. {install_message}")
[rank9]: ImportError: FlashAttention2 has been toggled on, but it cannot be used due to the following error: the package flash_attn seems to be not installed. Please refer to the documentation of https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-2 to install Flash Attention 2.
[rank8]: Traceback (most recent call last):
[rank8]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train_curriculum.py", line 235, in <module>
[rank8]:     main(get_train_data(CURRICULUM_STAGE), val_data, args.rank, args.learning_rate, args.total_epochs, args.beta, CURRICULUM_STAGE)
[rank8]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train_curriculum.py", line 149, in main
[rank8]:     model = AutoModelForCausalLM.from_pretrained(
[rank8]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
[rank8]:     return model_class.from_pretrained(
[rank8]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
[rank8]:     return func(*args, **kwargs)
[rank8]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4336, in from_pretrained
[rank8]:     config = cls._autoset_attn_implementation(
[rank8]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2109, in _autoset_attn_implementation
[rank8]:     cls._check_and_enable_flash_attn_2(
[rank8]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2252, in _check_and_enable_flash_attn_2
[rank8]:     raise ImportError(f"{preface} the package flash_attn seems to be not installed. {install_message}")
[rank8]: ImportError: FlashAttention2 has been toggled on, but it cannot be used due to the following error: the package flash_attn seems to be not installed. Please refer to the documentation of https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-2 to install Flash Attention 2.
[rank11]: Traceback (most recent call last):
[rank11]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train_curriculum.py", line 235, in <module>
[rank11]:     main(get_train_data(CURRICULUM_STAGE), val_data, args.rank, args.learning_rate, args.total_epochs, args.beta, CURRICULUM_STAGE)
[rank11]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train_curriculum.py", line 149, in main
[rank11]:     model = AutoModelForCausalLM.from_pretrained(
[rank11]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
[rank11]:     return model_class.from_pretrained(
[rank11]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
[rank11]:     return func(*args, **kwargs)
[rank11]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4336, in from_pretrained
[rank11]:     config = cls._autoset_attn_implementation(
[rank11]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2109, in _autoset_attn_implementation
[rank11]:     cls._check_and_enable_flash_attn_2(
[rank11]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2252, in _check_and_enable_flash_attn_2
[rank11]:     raise ImportError(f"{preface} the package flash_attn seems to be not installed. {install_message}")
[rank11]: ImportError: FlashAttention2 has been toggled on, but it cannot be used due to the following error: the package flash_attn seems to be not installed. Please refer to the documentation of https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-2 to install Flash Attention 2.
[rank10]: Traceback (most recent call last):
[rank10]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train_curriculum.py", line 235, in <module>
[rank10]:     main(get_train_data(CURRICULUM_STAGE), val_data, args.rank, args.learning_rate, args.total_epochs, args.beta, CURRICULUM_STAGE)
[rank10]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train_curriculum.py", line 149, in main
[rank10]:     model = AutoModelForCausalLM.from_pretrained(
[rank10]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
[rank10]:     return model_class.from_pretrained(
[rank10]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
[rank10]:     return func(*args, **kwargs)
[rank10]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4336, in from_pretrained
[rank10]:     config = cls._autoset_attn_implementation(
[rank10]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2109, in _autoset_attn_implementation
[rank10]:     cls._check_and_enable_flash_attn_2(
[rank10]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2252, in _check_and_enable_flash_attn_2
[rank10]:     raise ImportError(f"{preface} the package flash_attn seems to be not installed. {install_message}")
[rank10]: ImportError: FlashAttention2 has been toggled on, but it cannot be used due to the following error: the package flash_attn seems to be not installed. Please refer to the documentation of https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-2 to install Flash Attention 2.
[rank8]:[W608 19:24:53.858510403 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
W0608 19:24:54.622000 1922780 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1922965 closing signal SIGTERM
W0608 19:24:54.623000 1922780 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1922966 closing signal SIGTERM
W0608 19:24:54.623000 1922780 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1922967 closing signal SIGTERM
E0608 19:24:54.950000 1922780 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 1922964) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1182, in launch_command
    deepspeed_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 861, in deepspeed_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_curriculum.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-06-08_19:24:54
  host      : pm6-nod75.vega.pri
  rank      : 8 (local_rank: 0)
  exitcode  : 1 (pid: 1922964)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
