cpu-bind=MASK - gn08, task  1  0 [2493494]: mask 0xffff0000ffff0000ffffffffffffffffffff0000ffff0000ffffffffffffffff set
*******STARTING********
--- Running on Node Rank: 1 ---
Total Nodes: 2
--- CUDA_VISIBLE_DEVICES for this srun task: 0,1,2,3 ---
GPUs per Node: 4
Master Address: gn06
Master Port: 29500
-------------------------------------------
accelerate launch     --config_file /ceph/hpc/data/s24o01-42-users/translation_optimization/trl/accelerate_config.yaml     --num_machines 2     --machine_rank 1     --main_process_ip gn06     --main_process_port 29500     --num_processes 8     --deepspeed_hostfile /ceph/hpc/data/s24o01-42-users/translation_optimization/trl/result_dir/hostfile_62110685     --deepspeed_multinode_launcher standard     --rdzv_backend static     --same_network     --mixed_precision bf16     "train.py"     --rank=64 --learning_rate=3e-7 --total_epochs=3 --beta=0.2
-------------------------------------------
[2025-05-31 10:52:24,833] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
W0531 10:52:26.431000 2493544 torch/distributed/run.py:792] 
W0531 10:52:26.431000 2493544 torch/distributed/run.py:792] *****************************************
W0531 10:52:26.431000 2493544 torch/distributed/run.py:792] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0531 10:52:26.431000 2493544 torch/distributed/run.py:792] *****************************************
[2025-05-31 10:52:31,913] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-31 10:52:31,923] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-31 10:52:31,926] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-31 10:52:31,928] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Created datasets
Created datasetsNumber of training examples: 8564

Created datasetsNumber of training examples:Number of validation examples:  
Created datasets8564953Number of training examples:


 Number of validation examples:Number of training examples:8564  
9538564Number of validation examples:

 Number of validation examples:953 
953
Namespace(rank=64, learning_rate=3e-07, total_epochs=3, beta=0.2)Namespace(rank=64, learning_rate=3e-07, total_epochs=3, beta=0.2)
Namespace(rank=64, learning_rate=3e-07, total_epochs=3, beta=0.2)
Namespace(rank=64, learning_rate=3e-07, total_epochs=3, beta=0.2)3e-07
3e-07

3e-07
3e-07

World size: 8
Setting gradient accumulation steps to: 2
Created datasets
Steps per epoch: 4282
Eval steps: 2141
[2025-05-31 10:52:34,314] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-05-31 10:52:34,339] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-05-31 10:52:34,341] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-05-31 10:52:34,342] [INFO] [comm.py:658:init_distributed] cdb=None
Set up DPO configuration
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:19<00:58, 19.34s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:19<00:58, 19.44s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:19<00:58, 19.55s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:19<00:58, 19.58s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:36<00:36, 18.17s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:36<00:36, 18.22s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:37<00:36, 18.34s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:37<00:36, 18.34s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:57<00:19, 19.24s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:57<00:19, 19.23s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:57<00:19, 19.35s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:57<00:19, 19.28s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:14<00:00, 18.34s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:14<00:00, 18.55s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [01:14<00:00, 18.39s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:14<00:00, 18.61s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [01:14<00:00, 18.39s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:14<00:00, 18.62s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [01:14<00:00, 18.44s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:14<00:00, 18.62s/it]
/transformers/src/transformers/generation/configuration_utils.py:629: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/transformers/src/transformers/generation/configuration_utils.py:634: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/transformers/src/transformers/generation/configuration_utils.py:629: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/transformers/src/transformers/generation/configuration_utils.py:634: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Loaded model
/transformers/src/transformers/generation/configuration_utils.py:629: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/transformers/src/transformers/generation/configuration_utils.py:634: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/transformers/src/transformers/generation/configuration_utils.py:629: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/transformers/src/transformers/generation/configuration_utils.py:634: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]/transformers/src/transformers/generation/configuration_utils.py:629: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/transformers/src/transformers/generation/configuration_utils.py:634: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/transformers/src/transformers/generation/configuration_utils.py:629: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/transformers/src/transformers/generation/configuration_utils.py:634: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]/transformers/src/transformers/generation/configuration_utils.py:629: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/transformers/src/transformers/generation/configuration_utils.py:634: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/transformers/src/transformers/generation/configuration_utils.py:629: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/transformers/src/transformers/generation/configuration_utils.py:634: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:09<00:29,  9.71s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:09<00:29,  9.83s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:09<00:28,  9.58s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:09<00:29,  9.71s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:23<00:23, 11.84s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:23<00:23, 11.83s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:22<00:23, 11.75s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:22<00:23, 11.78s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:40<00:14, 14.54s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:40<00:14, 14.44s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:40<00:14, 14.51s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:40<00:14, 14.57s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:36<00:00, 30.63s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:36<00:00, 24.03s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [01:35<00:00, 30.62s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:35<00:00, 23.98s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [01:36<00:00, 30.64s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:36<00:00, 24.02s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [01:36<00:00, 30.69s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:36<00:00, 24.07s/it]
[rank5]: Traceback (most recent call last):
[rank5]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 207, in <module>
[rank5]:     main(train_data, val_data, args.rank, args.learning_rate, args.total_epochs, args.beta)
[rank5]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 175, in main
[rank5]:     dpo_trainer = DPOTrainer(
[rank5]:   File "/transformers/src/transformers/utils/deprecation.py", line 172, in wrapped_func
[rank5]:     return func(*args, **kwargs)
[rank5]:   File "/usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py", line 230, in __init__
[rank5]:     raise ValueError(
[rank5]: ValueError: `model` and `ref_model` cannot be the same object. If you want `ref_model` to be the same as `model`, you must mass a copy of it, or `None` if you use peft.
Using LoRA and set up the model
Loaded tokenizer
[rank4]: Traceback (most recent call last):
[rank4]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 207, in <module>
[rank4]:     main(train_data, val_data, args.rank, args.learning_rate, args.total_epochs, args.beta)
[rank4]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 175, in main
[rank4]:     dpo_trainer = DPOTrainer(
[rank4]:   File "/transformers/src/transformers/utils/deprecation.py", line 172, in wrapped_func
[rank4]:     return func(*args, **kwargs)
[rank4]:   File "/usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py", line 230, in __init__
[rank4]:     raise ValueError(
[rank4]: ValueError: `model` and `ref_model` cannot be the same object. If you want `ref_model` to be the same as `model`, you must mass a copy of it, or `None` if you use peft.
[rank7]: Traceback (most recent call last):
[rank7]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 207, in <module>
[rank7]:     main(train_data, val_data, args.rank, args.learning_rate, args.total_epochs, args.beta)
[rank7]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 175, in main
[rank7]:     dpo_trainer = DPOTrainer(
[rank7]:   File "/transformers/src/transformers/utils/deprecation.py", line 172, in wrapped_func
[rank7]:     return func(*args, **kwargs)
[rank7]:   File "/usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py", line 230, in __init__
[rank7]:     raise ValueError(
[rank7]: ValueError: `model` and `ref_model` cannot be the same object. If you want `ref_model` to be the same as `model`, you must mass a copy of it, or `None` if you use peft.
[rank6]: Traceback (most recent call last):
[rank6]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 207, in <module>
[rank6]:     main(train_data, val_data, args.rank, args.learning_rate, args.total_epochs, args.beta)
[rank6]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 175, in main
[rank6]:     dpo_trainer = DPOTrainer(
[rank6]:   File "/transformers/src/transformers/utils/deprecation.py", line 172, in wrapped_func
[rank6]:     return func(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py", line 230, in __init__
[rank6]:     raise ValueError(
[rank6]: ValueError: `model` and `ref_model` cannot be the same object. If you want `ref_model` to be the same as `model`, you must mass a copy of it, or `None` if you use peft.
W0531 10:55:40.051000 2493544 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2493734 closing signal SIGTERM
W0531 10:55:40.064000 2493544 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2493736 closing signal SIGTERM
W0531 10:55:40.064000 2493544 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2493737 closing signal SIGTERM
E0531 10:55:41.408000 2493544 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 1 (pid: 2493735) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1182, in launch_command
    deepspeed_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 861, in deepspeed_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-31_10:55:40
  host      : pm5-nod21.vega.pri
  rank      : 5 (local_rank: 1)
  exitcode  : 1 (pid: 2493735)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
